# Generated by Django 5.2.9 on 2026-01-04 20:00

import django.db.models.deletion
import django_ckeditor_5.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmailTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="A unique name to identify the template, e.g., 'account_confirmation'.", max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='EmailTemplateTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(choices=[('ca', 'Catalan'), ('en', 'English'), ('es', 'Spanish'), ('fr', 'French'), ('de', 'German'), ('it', 'Italian'), ('pt', 'Portuguese')], max_length=10)),
                ('subject', models.CharField(max_length=255)),
                ('body', django_ckeditor_5.fields.CKEditor5Field()),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='post_office.emailtemplate')),
            ],
            options={
                'unique_together': {('template', 'language')},
            },
        ),
    ]
