# Generated by Django 5.2.9 on 2025-12-23 15:05

import django.db.models.deletion
import django_ckeditor_5.fields
from django.db import migrations, models

def create_initial_email_templates(apps, schema_editor):
    EmailTemplate = apps.get_model('post_office', 'EmailTemplate')
    EmailTemplateTranslation = apps.get_model('post_office', 'EmailTemplateTranslation')

    # Account Confirmation Email
    account_confirmation = EmailTemplate.objects.create(name='account_confirmation')
    EmailTemplateTranslation.objects.create(
        template=account_confirmation,
        language='ca',
        subject='Confirma el teu compte a Audiovook',
        body="""
        <h2>Benvingut/da a Audiovook, {{ user.first_name }}!</h2>
        <p>Gràcies per registrar-te. Si us plau, fes clic a l'enllaç següent per activar el teu compte:</p>
        <a href="{{ token_url }}">Activa el teu compte</a>
        <p>Si no has creat aquest compte, si us plau, ignora aquest correu.</p>
        <p>L'equip d'Audiovook</p>
        """
    )
    EmailTemplateTranslation.objects.create(
        template=account_confirmation,
        language='en',
        subject='Confirm your account at Audiovook',
        body="""
        <h2>Welcome to Audiovook, {{ user.first_name }}!</h2>
        <p>Thanks for signing up. Please click the link below to activate your account:</p>
        <a href="{{ token_url }}">Activate your account</a>
        <p>If you did not create this account, please ignore this email.</p>
        <p>The Audiovook Team</p>
        """
    )
    EmailTemplateTranslation.objects.create(
        template=account_confirmation,
        language='es',
        subject='Confirma tu cuenta en Audiovook',
        body="""
        <h2>¡Bienvenido/a a Audiovook, {{ user.first_name }}!</h2>
        <p>Gracias por registrarte. Por favor, haz clic en el siguiente enlace para activar tu cuenta:</p>
        <a href="{{ token_url }}">Activa tu cuenta</a>
        <p>Si no has creado esta cuenta, por favor, ignora este correo.</p>
        <p>El equipo de Audiovook</p>
        """
    )

    # Password Reset Email
    password_reset = EmailTemplate.objects.create(name='password_reset')
    EmailTemplateTranslation.objects.create(
        template=password_reset,
        language='ca',
        subject='Restabliment de la contrasenya',
        body="""
        <p>Hola,</p>
        <p>Has sol·licitat restablir la teva contrasenya a Audiovook. Fes clic a l'enllaç següent per establir una nova contrasenya:</p>
        <p><a href="{{ protocol }}://{{ domain }}{% url 'accounts:password_reset_confirm' uidb64=uid token=token %}">Restablir la contrasenya</a></p>
        <p>Si no has sol·licitat aquest canvi, pots ignorar aquest correu electrònic.</p>
        <p>Gràcies,</p>
        <p>L'equip d'Audiovook</p>
        """
    )
    EmailTemplateTranslation.objects.create(
        template=password_reset,
        language='en',
        subject='Password Reset',
        body="""
        <p>Hello,</p>
        <p>You have requested to reset your password at Audiovook. Click the link below to set a new password:</p>
        <p><a href="{{ protocol }}://{{ domain }}{% url 'accounts:password_reset_confirm' uidb64=uid token=token %}">Reset your password</a></p>
        <p>If you did not request this change, you can ignore this email.</p>
        <p>Thanks,</p>
        <p>The Audiovook Team</p>
        """
    )
    EmailTemplateTranslation.objects.create(
        template=password_reset,
        language='es',
        subject='Restablecimiento de contraseña',
        body="""
        <p>Hola,</p>
        <p>Has solicitado restablecer tu contraseña en Audiovook. Haz clic en el siguiente enlace para establecer una nueva contraseña:</p>
        <p><a href="{{ protocol }}://{{ domain }}{% url 'accounts:password_reset_confirm' uidb64=uid token=token %}">Restablecer la contraseña</a></p>
        <p>Si no has solicitado este cambio, puedes ignorar este correo electrónico.</p>
        <p>Gracias,</p>
        <p>El equipo de Audiovook</p>
        """
    )


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="EmailTemplate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="A unique name to identify the template, e.g., 'account_confirmation'.",
                        max_length=255,
                        unique=True,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="EmailTemplateTranslation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "language",
                    models.CharField(
                        choices=[
                            ("ca", "Catalan"),
                            ("en", "English"),
                            ("es", "Spanish"),
                            ("fr", "French"),
                            ("de", "German"),
                            ("it", "Italian"),
                            ("pt", "Portuguese"),
                        ],
                        max_length=10,
                    ),
                ),
                ("subject", models.CharField(max_length=255)),
                ("body", django_ckeditor_5.fields.CKEditor5Field()),
                (
                    "template",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="translations",
                        to="post_office.emailtemplate",
                    ),
                ),
            ],
            options={
                "unique_together": {("template", "language")},
            },
        ),
        migrations.RunPython(create_initial_email_templates),
    ]
