# Generated by Django 5.2.9 on 2026-01-03 00:00

from django.db import migrations

def correct_spanish_welcome_email(apps, schema_editor):
    EmailTemplateTranslation = apps.get_model('post_office', 'EmailTemplateTranslation')
    try:
        # Find the Spanish translation for the account confirmation email
        translation = EmailTemplateTranslation.objects.get(
            template__name='account_confirmation',
            language='es'
        )

        # Correct the body content
        translation.body = """
        <h2>¡Bienvenido/a a Dual, {{ user.first_name }}!</h2>
        <p>Gracias por registrarte. Por favor, haz clic en el siguiente enlace para activar tu cuenta:</p>
        <a href="{{ token_url }}">Activa tu cuenta</a>
        <p>Si no has creado esta cuenta, por favor, ignora este correo.</p>
        <p>El equipo de Dual</p>
        """
        translation.save()
    except EmailTemplateTranslation.DoesNotExist:
        # If the template doesn't exist for some reason, do nothing.
        pass

class Migration(migrations.Migration):

    dependencies = [
        ('post_office', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(correct_spanish_welcome_email),
    ]
