# Generated by Django 5.2.10 on 2026-01-15 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("post_office", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="emailtemplatetranslation",
            name="plain_body",
            field=models.TextField(
                blank=True,
                default="",
                help_text="Plain text version of the email body.",
                null=True,
            ),
        ),
    ]
