# Generated by Django 5.2.9 on 2025-12-23 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("post_office", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="emailtemplatetranslation",
            name="language",
            field=models.CharField(
                choices=[
                    ("ca", "Catalan"),
                    ("en", "English"),
                    ("es", "Spanish"),
                    ("fr", "French"),
                    ("de", "German"),
                    ("it", "Italian"),
                    ("pt", "Portuguese"),
                ],
                max_length=10,
            ),
        ),
    ]
