# Generated by Django 5.2.8 on 2025-11-24 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
        ("products", "0003_alter_package_id_alter_product_id_alter_title_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="packages",
            field=models.ManyToManyField(
                blank=True,
                help_text="Els paquets als que aquest usuari té accés.",
                related_name="users",
                to="products.package",
                verbose_name="paquets",
            ),
        ),
    ]
