# Generated by Django 5.2.8 on 2025-11-26 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_alter_customuser_email"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="known_languages",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="Llista de llengües que l'usuari coneix i el seu nivell.",
                verbose_name="Llengües conegudes",
            ),
        ),
        migrations.AddField(
            model_name="customuser",
            name="learning_languages",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="Llista de llengües que l'usuari vol aprendre i el seu nivell.",
                verbose_name="Llengües a aprendre",
            ),
        ),
    ]
