# Generated by Django 5.2.9 on 2025-12-02 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0004_customuser_known_languages_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="confirmation_token",
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="customuser",
            name="email_confirmed",
            field=models.BooleanField(default=False),
        ),
    ]
