# Generated by Django 5.2.10 on 2026-01-27 12:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0004_alter_customuser_first_name_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="customuser",
            options={
                "verbose_name": "Administrator",
                "verbose_name_plural": "Administrators",
            },
        ),
    ]
