# Generated by Django 5.2.10 on 2026-01-27 16:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0006_set_site_domain"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="customuser",
            options={"verbose_name": "User", "verbose_name_plural": "Users"},
        ),
    ]
