# Generated by Django 5.2.10 on 2026-01-27 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0007_alter_customuser_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="is_first_login",
            field=models.BooleanField(default=True),
        ),
    ]
