# Generated by Django 5.2.11 on 2026-02-04 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0008_customuser_is_first_login"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="language_code",
            field=models.CharField(
                default="ca",
                help_text="The user's preferred language for communication.",
                max_length=10,
                verbose_name="language code",
            ),
        ),
    ]
