# Generated by Django 5.2.8 on 2025-11-21 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Title",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "slug",
                    models.SlugField(
                        help_text="Identificador únic del títol", unique=True
                    ),
                ),
                (
                    "title_human",
                    models.CharField(help_text="Títol llegible", max_length=255),
                ),
                ("description", models.TextField(blank=True)),
                (
                    "level",
                    models.CharField(
                        help_text="Nivell del títol (A0, A1, …)", max_length=10
                    ),
                ),
                (
                    "languages",
                    models.CharField(
                        help_text="Idiomes separats per comes", max_length=255
                    ),
                ),
                (
                    "ages",
                    models.CharField(
                        blank=True, help_text="Rang d'edat recomanat", max_length=50
                    ),
                ),
                ("collection", models.CharField(blank=True, max_length=255)),
                ("duration", models.CharField(blank=True, max_length=20)),
            ],
            options={
                "ordering": ["title_human"],
            },
        ),
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                (
                    "level",
                    models.CharField(
                        blank=True,
                        help_text="Nivell del paquet (per exemple A0, A1, A2, B1, B2, C1, C2)",
                        max_length=10,
                    ),
                ),
                (
                    "language_pair",
                    models.CharField(
                        help_text="Exemple: Català - Anglès", max_length=100
                    ),
                ),
                ("description", models.TextField()),
                (
                    "price",
                    models.DecimalField(decimal_places=2, default=0, max_digits=6),
                ),
                (
                    "audio_file",
                    models.FileField(
                        blank=True,
                        help_text="Arxiu d'àudio opcional",
                        null=True,
                        upload_to="audios/",
                    ),
                ),
                (
                    "cover_image",
                    models.CharField(
                        blank=True,
                        help_text="Ruta de la imatge a /static/imgs o /media",
                        max_length=255,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "titles",
                    models.ManyToManyField(
                        blank=True, related_name="products", to="products.title"
                    ),
                ),
            ],
            options={
                "ordering": ["title"],
            },
        ),
    ]
