# Generated by Django 5.2.8 on 2025-11-21 17:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Package",
            fields=[
                (
                    "id",
                    models.CharField(
                        help_text="ID del paquet, p. ex., 20001",
                        max_length=5,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(help_text="Nom del paquet", max_length=255)),
                (
                    "level_range",
                    models.CharField(
                        blank=True,
                        help_text="Rang de nivells del paquet, p. ex., 'A0'",
                        max_length=50,
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, help_text="Descripció del paquet"),
                ),
                (
                    "is_free",
                    models.BooleanField(
                        default=False, help_text="És un paquet gratuït?"
                    ),
                ),
            ],
            options={
                "verbose_name": "Paquet",
                "verbose_name_plural": "Paquets",
            },
        ),
        migrations.CreateModel(
            name="Title",
            fields=[
                (
                    "id",
                    models.CharField(
                        help_text="ID del títol, p. ex., 10001",
                        max_length=5,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "machine_name",
                    models.SlugField(
                        help_text="Nom intern sense espais, p. ex., 'el-meu-titol'",
                        unique=True,
                    ),
                ),
                (
                    "human_name",
                    models.CharField(
                        help_text="Nom del títol per mostrar", max_length=255
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, help_text="Descripció del títol"),
                ),
                (
                    "levels",
                    models.CharField(
                        blank=True, help_text="Nivells, p. ex., 'A2'", max_length=50
                    ),
                ),
                (
                    "langs",
                    models.CharField(
                        blank=True,
                        help_text="Idiomes separats per comes, p. ex., 'CA, EN, FR'",
                        max_length=100,
                    ),
                ),
                (
                    "ages",
                    models.CharField(
                        blank=True,
                        help_text="Rang d’edat, p. ex., '10-16'",
                        max_length=20,
                    ),
                ),
                (
                    "collection",
                    models.CharField(
                        blank=True,
                        help_text="Col·lecció a la qual pertany",
                        max_length=100,
                    ),
                ),
                (
                    "duration",
                    models.CharField(
                        blank=True, help_text="Durada en format HH:MM:SS", max_length=20
                    ),
                ),
            ],
            options={
                "verbose_name": "Títol",
                "verbose_name_plural": "Títols",
            },
        ),
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.CharField(
                        help_text="ID del producte, p. ex., 30001",
                        max_length=5,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "name",
                    models.CharField(help_text="Nom del producte", max_length=255),
                ),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=2, help_text="Preu del producte", max_digits=10
                    ),
                ),
                (
                    "currency",
                    models.CharField(
                        default="euro", help_text="Moneda del preu", max_length=10
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, help_text="Descripció del producte"),
                ),
                (
                    "is_free",
                    models.BooleanField(
                        default=False, help_text="És un producte gratuït?"
                    ),
                ),
                (
                    "packages",
                    models.ManyToManyField(
                        help_text="Paquets inclosos en aquest producte",
                        related_name="products",
                        to="products.package",
                    ),
                ),
            ],
            options={
                "verbose_name": "Producte",
                "verbose_name_plural": "Productes",
            },
        ),
        migrations.AddField(
            model_name="package",
            name="titles",
            field=models.ManyToManyField(
                help_text="Títols inclosos en aquest paquet",
                related_name="packages",
                to="products.title",
            ),
        ),
        migrations.CreateModel(
            name="UserPurchase",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("purchase_date", models.DateTimeField(auto_now_add=True)),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="purchases",
                        to="products.product",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="purchases",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Compra d'usuari",
                "verbose_name_plural": "Compres d'usuaris",
                "unique_together": {("user", "product")},
            },
        ),
    ]
