# Generated by Django 5.2.9 on 2026-01-04 20:00

import django.db.models.deletion
import django_ckeditor_5.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HomePageContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_ca', models.TextField(blank=True, verbose_name='Home-Page_Content (Català)')),
                ('content_en', models.TextField(blank=True, verbose_name='Home-Page_Content (English)')),
                ('content_es', models.TextField(blank=True, verbose_name='Home-Page_Content (Español)')),
                ('content_fr', models.TextField(blank=True, verbose_name='Home-Page_Content (Français)')),
                ('content_pt', models.TextField(blank=True, verbose_name='Home-Page_Content (Português)')),
                ('content_de', models.TextField(blank=True, verbose_name='Home-Page_Content (Deutsch)')),
                ('content_it', models.TextField(blank=True, verbose_name='Home-Page_Content (Italiano)')),
            ],
            options={
                'verbose_name': 'Homepage Content',
                'verbose_name_plural': 'Homepage Content',
            },
        ),
        migrations.CreateModel(
            name='Package',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Nom del paquet', max_length=255)),
                ('level', models.CharField(choices=[('A0', 'A0'), ('A1', 'A1'), ('A2', 'A2'), ('B1', 'B1'), ('B2', 'B2'), ('C1', 'C1')], help_text='Nivell del paquet', max_length=2)),
            ],
            options={
                'verbose_name': 'Paquet',
                'verbose_name_plural': 'Paquets',
            },
        ),
        migrations.CreateModel(
            name='Title',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('machine_name', models.SlugField(help_text="Nom intern sense espais, p. ex., 'el-meu-titol'", unique=True)),
                ('level', models.CharField(blank=True, help_text="Nivell, p. ex., 'A2'", max_length=50)),
            ],
            options={
                'verbose_name': 'Títol',
                'verbose_name_plural': 'Títols',
            },
        ),
        migrations.CreateModel(
            name='TranslatableContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(help_text="Clau única per identificar el contingut, p. ex., 'home_page_main_content'", max_length=100, unique=True)),
                ('content_ca', django_ckeditor_5.fields.CKEditor5Field(blank=True, verbose_name='Contingut (Català)')),
                ('content_en', django_ckeditor_5.fields.CKEditor5Field(blank=True, verbose_name='Contingut (English)')),
                ('content_es', django_ckeditor_5.fields.CKEditor5Field(blank=True, verbose_name='Contingut (Español)')),
                ('content_fr', django_ckeditor_5.fields.CKEditor5Field(blank=True, verbose_name='Contingut (Français)')),
                ('content_pt', django_ckeditor_5.fields.CKEditor5Field(blank=True, verbose_name='Contingut (Português)')),
                ('content_de', django_ckeditor_5.fields.CKEditor5Field(blank=True, verbose_name='Contingut (Deutsch)')),
                ('content_it', django_ckeditor_5.fields.CKEditor5Field(blank=True, verbose_name='Contingut (Italiano)')),
            ],
            options={
                'verbose_name': 'Contingut Traduïble',
                'verbose_name_plural': 'Continguts Traduïbles',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('price', models.DecimalField(decimal_places=2, help_text='Preu del producte', max_digits=10)),
                ('currency', models.CharField(default='euro', help_text='Moneda del preu', max_length=10)),
                ('duration', models.IntegerField(default=0, help_text='Durada del producte en mesos')),
                ('category', models.CharField(blank=True, help_text='Categoria del producte', max_length=50)),
                ('packages', models.ManyToManyField(help_text='Paquets inclosos en aquest producte', related_name='products', to='products.package')),
            ],
            options={
                'verbose_name': 'Producte',
                'verbose_name_plural': 'Productes',
            },
        ),
        migrations.AddField(
            model_name='package',
            name='titles',
            field=models.ManyToManyField(help_text='Títols inclosos en aquest paquet', related_name='packages', to='products.title'),
        ),
        migrations.CreateModel(
            name='ProductTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(max_length=10)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='products.product')),
            ],
            options={
                'verbose_name': 'Traducció de Producte',
                'verbose_name_plural': 'Traduccions de Producte',
                'unique_together': {('product', 'language_code')},
            },
        ),
        migrations.CreateModel(
            name='UserPurchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purchase_date', models.DateTimeField(auto_now_add=True)),
                ('expiry_date', models.DateTimeField(blank=True, null=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchases', to='products.product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchases', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': "Compra d'usuari",
                'verbose_name_plural': "Compres d'usuaris",
                'unique_together': {('user', 'product')},
            },
        ),
    ]
