# Generated by Django 5.2.8 on 2025-11-21 20:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="title",
            name="langs",
        ),
        migrations.CreateModel(
            name="TitleLanguage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "language",
                    models.CharField(
                        help_text="Codi de l'idioma, p. ex., 'CA'", max_length=2
                    ),
                ),
                (
                    "directory",
                    models.CharField(
                        help_text="Ruta al directori de l'idioma", max_length=255
                    ),
                ),
                (
                    "json_file",
                    models.CharField(
                        help_text="Nom del fitxer JSON de l'idioma", max_length=255
                    ),
                ),
                (
                    "title",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="languages",
                        to="products.title",
                    ),
                ),
            ],
            options={
                "verbose_name": "Ruta d'idioma del títol",
                "verbose_name_plural": "Rutes d'idioma del títol",
                "unique_together": {("title", "language")},
            },
        ),
    ]
