# Generated by Django 5.2.8 on 2025-11-21 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="level",
            field=models.CharField(
                blank=True,
                help_text="Nivell del paquet (per exemple A0, A1, A2, B1, B2, C1, C2)",
                max_length=10,
            ),
        ),
    ]
