# Generated by Django 5.2.9 on 2026-01-05 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="machine_name",
            field=models.SlugField(
                blank=True,
                help_text="Nom intern sense espais, p. ex., 'el-meu-producte'",
                unique=True,
            ),
        ),
    ]
