# Generated by Django 5.2.8 on 2025-11-21 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0002_product_level"),
    ]

    operations = [
        migrations.CreateModel(
            name="Title",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "slug",
                    models.SlugField(
                        help_text="Identificador únic del títol", unique=True
                    ),
                ),
                (
                    "title_human",
                    models.CharField(help_text="Títol llegible", max_length=255),
                ),
                ("description", models.TextField(blank=True)),
                (
                    "level",
                    models.CharField(
                        help_text="Nivell del títol (A0, A1, …)", max_length=10
                    ),
                ),
                (
                    "languages",
                    models.CharField(
                        help_text="Idiomes separats per comes", max_length=255
                    ),
                ),
                (
                    "ages",
                    models.CharField(
                        blank=True, help_text="Rang d'edat recomanat", max_length=50
                    ),
                ),
                ("collection", models.CharField(blank=True, max_length=255)),
                ("duration", models.CharField(blank=True, max_length=20)),
            ],
            options={
                "ordering": ["title_human"],
            },
        ),
        migrations.AddField(
            model_name="product",
            name="titles",
            field=models.ManyToManyField(
                blank=True, related_name="products", to="products.title"
            ),
        ),
    ]
