# Generated by Django 5.2.9 on 2026-01-05 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0002_product_machine_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="machine_name",
            field=models.SlugField(
                help_text="Nom intern sense espais, p. ex., 'el-meu-producte'",
                unique=True,
            ),
        ),
    ]
