# Generated by Django 5.2.8 on 2025-11-24 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0002_remove_title_langs_titlelanguage"),
    ]

    operations = [
        migrations.AlterField(
            model_name="package",
            name="id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name="product",
            name="id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name="title",
            name="id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
