# Generated by Django 5.2.8 on 2025-11-26 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0003_alter_package_id_alter_product_id_alter_title_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="package",
            name="is_default_free",
            field=models.BooleanField(
                default=False,
                help_text="Marca si aquest és el paquet gratuït per defecte per a nous usuaris",
            ),
        ),
    ]
