# Generated by Django 5.2.9 on 2026-01-05 16:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0003_alter_product_machine_name"),
    ]

    operations = [
        migrations.CreateModel(
            name="TitleTranslation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("language_code", models.CharField(max_length=10)),
                ("human_name", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True)),
                (
                    "title",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="translations",
                        to="products.title",
                    ),
                ),
            ],
            options={
                "verbose_name": "Traducció de Títol",
                "verbose_name_plural": "Traduccions de Títol",
                "unique_together": {("title", "language_code")},
            },
        ),
    ]
