# Generated by Django 5.2.8 on 2025-11-29 17:45

import django_ckeditor_5.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0004_package_is_default_free"),
    ]

    operations = [
        migrations.CreateModel(
            name="TranslatableContent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "key",
                    models.CharField(
                        help_text="Clau única per identificar el contingut, p. ex., 'home_page_main_content'",
                        max_length=100,
                        unique=True,
                    ),
                ),
                (
                    "content_ca",
                    django_ckeditor_5.fields.CKEditor5Field(
                        blank=True, verbose_name="Contingut (Català)"
                    ),
                ),
                (
                    "content_en",
                    django_ckeditor_5.fields.CKEditor5Field(
                        blank=True, verbose_name="Contingut (English)"
                    ),
                ),
                (
                    "content_es",
                    django_ckeditor_5.fields.CKEditor5Field(
                        blank=True, verbose_name="Contingut (Español)"
                    ),
                ),
                (
                    "content_fr",
                    django_ckeditor_5.fields.CKEditor5Field(
                        blank=True, verbose_name="Contingut (Français)"
                    ),
                ),
                (
                    "content_pt",
                    django_ckeditor_5.fields.CKEditor5Field(
                        blank=True, verbose_name="Contingut (Português)"
                    ),
                ),
                (
                    "content_de",
                    django_ckeditor_5.fields.CKEditor5Field(
                        blank=True, verbose_name="Contingut (Deutsch)"
                    ),
                ),
                (
                    "content_it",
                    django_ckeditor_5.fields.CKEditor5Field(
                        blank=True, verbose_name="Contingut (Italiano)"
                    ),
                ),
            ],
            options={
                "verbose_name": "Contingut Traduïble",
                "verbose_name_plural": "Continguts Traduïbles",
            },
        ),
    ]
