# Generated by Django 5.2.10 on 2026-01-13 12:07

import django_ckeditor_5.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0004_titletranslation"),
    ]

    operations = [
        migrations.AlterField(
            model_name="producttranslation",
            name="description",
            field=django_ckeditor_5.fields.CKEditor5Field(
                blank=True, verbose_name="Description"
            ),
        ),
    ]
