# Generated by Django 5.2.8 on 2025-11-30 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0005_translatablecontent"),
    ]

    operations = [
        migrations.AlterField(
            model_name="translatablecontent",
            name="content_ca",
            field=models.TextField(blank=True, verbose_name="Contingut (Català)"),
        ),
        migrations.AlterField(
            model_name="translatablecontent",
            name="content_de",
            field=models.TextField(blank=True, verbose_name="Contingut (Deutsch)"),
        ),
        migrations.AlterField(
            model_name="translatablecontent",
            name="content_en",
            field=models.TextField(blank=True, verbose_name="Contingut (English)"),
        ),
        migrations.AlterField(
            model_name="translatablecontent",
            name="content_es",
            field=models.TextField(blank=True, verbose_name="Contingut (Español)"),
        ),
        migrations.AlterField(
            model_name="translatablecontent",
            name="content_fr",
            field=models.TextField(blank=True, verbose_name="Contingut (Français)"),
        ),
        migrations.AlterField(
            model_name="translatablecontent",
            name="content_it",
            field=models.TextField(blank=True, verbose_name="Contingut (Italiano)"),
        ),
        migrations.AlterField(
            model_name="translatablecontent",
            name="content_pt",
            field=models.TextField(blank=True, verbose_name="Contingut (Português)"),
        ),
    ]
