# Generated by Django 5.2.10 on 2026-01-13 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0006_useractivity"),
    ]

    operations = [
        migrations.AddField(
            model_name="useractivity",
            name="listen_count",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
