# Generated by Django 5.2.8 on 2025-11-30 16:38

import django_ckeditor_5.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0006_alter_translatablecontent_content_ca_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="translatablecontent",
            name="content_ca",
            field=django_ckeditor_5.fields.CKEditor5Field(
                blank=True, verbose_name="Contingut (Català)"
            ),
        ),
        migrations.AlterField(
            model_name="translatablecontent",
            name="content_de",
            field=django_ckeditor_5.fields.CKEditor5Field(
                blank=True, verbose_name="Contingut (Deutsch)"
            ),
        ),
        migrations.AlterField(
            model_name="translatablecontent",
            name="content_en",
            field=django_ckeditor_5.fields.CKEditor5Field(
                blank=True, verbose_name="Contingut (English)"
            ),
        ),
        migrations.AlterField(
            model_name="translatablecontent",
            name="content_es",
            field=django_ckeditor_5.fields.CKEditor5Field(
                blank=True, verbose_name="Contingut (Español)"
            ),
        ),
        migrations.AlterField(
            model_name="translatablecontent",
            name="content_fr",
            field=django_ckeditor_5.fields.CKEditor5Field(
                blank=True, verbose_name="Contingut (Français)"
            ),
        ),
        migrations.AlterField(
            model_name="translatablecontent",
            name="content_it",
            field=django_ckeditor_5.fields.CKEditor5Field(
                blank=True, verbose_name="Contingut (Italiano)"
            ),
        ),
        migrations.AlterField(
            model_name="translatablecontent",
            name="content_pt",
            field=django_ckeditor_5.fields.CKEditor5Field(
                blank=True, verbose_name="Contingut (Português)"
            ),
        ),
    ]
