# Generated by Django 5.2.10 on 2026-01-28 13:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0007_useractivity_listen_count"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="userpurchase",
            unique_together=set(),
        ),
        migrations.AddField(
            model_name="userpurchase",
            name="paid_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="userpurchase",
            name="payment_provider",
            field=models.CharField(default="paypal", max_length=50),
        ),
        migrations.AddField(
            model_name="userpurchase",
            name="paypal_capture_id",
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AddField(
            model_name="userpurchase",
            name="paypal_order_id",
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AddField(
            model_name="userpurchase",
            name="status",
            field=models.CharField(
                choices=[
                    ("completed", "Completed"),
                    ("refunded", "Refunded"),
                    ("failed", "Failed"),
                ],
                default="completed",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="userpurchase",
            name="user_email",
            field=models.EmailField(blank=True, max_length=255),
        ),
        migrations.CreateModel(
            name="UserAccess",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("active", models.BooleanField(default=True)),
                ("activated_at", models.DateTimeField(auto_now_add=True)),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="accesses",
                        to="products.product",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="accesses",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Accés d'usuari",
                "verbose_name_plural": "Accessos d'usuaris",
                "unique_together": {("user", "product")},
            },
        ),
    ]
