# Generated by Django 5.2.8 on 2025-11-30 17:08

import django_ckeditor_5.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0007_alter_translatablecontent_content_ca_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="HomePageContent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "kicker_ca",
                    django_ckeditor_5.fields.CKEditor5Field(
                        blank=True, verbose_name="Kicker (Català)"
                    ),
                ),
                (
                    "kicker_en",
                    django_ckeditor_5.fields.CKEditor5Field(
                        blank=True, verbose_name="Kicker (English)"
                    ),
                ),
                (
                    "cta_title_ca",
                    django_ckeditor_5.fields.CKEditor5Field(
                        blank=True, verbose_name="Títol CTA (Català)"
                    ),
                ),
                (
                    "cta_title_en",
                    django_ckeditor_5.fields.CKEditor5Field(
                        blank=True, verbose_name="CTA Title (English)"
                    ),
                ),
                (
                    "cta_subtitle_ca",
                    django_ckeditor_5.fields.CKEditor5Field(
                        blank=True, verbose_name="Subtítol CTA (Català)"
                    ),
                ),
                (
                    "cta_subtitle_en",
                    django_ckeditor_5.fields.CKEditor5Field(
                        blank=True, verbose_name="CTA Subtitle (English)"
                    ),
                ),
                (
                    "discover_products_ca",
                    django_ckeditor_5.fields.CKEditor5Field(
                        blank=True, verbose_name="Descobreix Productes (Català)"
                    ),
                ),
                (
                    "discover_products_en",
                    django_ckeditor_5.fields.CKEditor5Field(
                        blank=True, verbose_name="Discover Products (English)"
                    ),
                ),
                (
                    "create_account_ca",
                    django_ckeditor_5.fields.CKEditor5Field(
                        blank=True, verbose_name="Crea un compte (Català)"
                    ),
                ),
                (
                    "create_account_en",
                    django_ckeditor_5.fields.CKEditor5Field(
                        blank=True, verbose_name="Create Account (English)"
                    ),
                ),
                (
                    "products_ca",
                    django_ckeditor_5.fields.CKEditor5Field(
                        blank=True, verbose_name="Productes (Català)"
                    ),
                ),
                (
                    "products_en",
                    django_ckeditor_5.fields.CKEditor5Field(
                        blank=True, verbose_name="Products (English)"
                    ),
                ),
                (
                    "short_stories_ca",
                    django_ckeditor_5.fields.CKEditor5Field(
                        blank=True, verbose_name="Històries Curtes (Català)"
                    ),
                ),
                (
                    "short_stories_en",
                    django_ckeditor_5.fields.CKEditor5Field(
                        blank=True, verbose_name="Short Stories (English)"
                    ),
                ),
                (
                    "browse_catalog_ca",
                    django_ckeditor_5.fields.CKEditor5Field(
                        blank=True, verbose_name="Consulta el catàleg (Català)"
                    ),
                ),
                (
                    "browse_catalog_en",
                    django_ckeditor_5.fields.CKEditor5Field(
                        blank=True, verbose_name="Browse Catalog (English)"
                    ),
                ),
                (
                    "add_new_product_ca",
                    django_ckeditor_5.fields.CKEditor5Field(
                        blank=True, verbose_name="Afegir Nou Producte (Català)"
                    ),
                ),
                (
                    "add_new_product_en",
                    django_ckeditor_5.fields.CKEditor5Field(
                        blank=True, verbose_name="Add New Product (English)"
                    ),
                ),
                (
                    "package_ca",
                    django_ckeditor_5.fields.CKEditor5Field(
                        blank=True, verbose_name="Paquet (Català)"
                    ),
                ),
                (
                    "package_en",
                    django_ckeditor_5.fields.CKEditor5Field(
                        blank=True, verbose_name="Package (English)"
                    ),
                ),
                (
                    "included_titles_ca",
                    django_ckeditor_5.fields.CKEditor5Field(
                        blank=True, verbose_name="Títols Inclosos (Català)"
                    ),
                ),
                (
                    "included_titles_en",
                    django_ckeditor_5.fields.CKEditor5Field(
                        blank=True, verbose_name="Included Titles (English)"
                    ),
                ),
                (
                    "no_titles_in_package_ca",
                    django_ckeditor_5.fields.CKEditor5Field(
                        blank=True, verbose_name="Sense Títols (Català)"
                    ),
                ),
                (
                    "no_titles_in_package_en",
                    django_ckeditor_5.fields.CKEditor5Field(
                        blank=True, verbose_name="No Titles (English)"
                    ),
                ),
                (
                    "view_details_ca",
                    django_ckeditor_5.fields.CKEditor5Field(
                        blank=True, verbose_name="Veure Fitxa (Català)"
                    ),
                ),
                (
                    "view_details_en",
                    django_ckeditor_5.fields.CKEditor5Field(
                        blank=True, verbose_name="View Details (English)"
                    ),
                ),
                (
                    "no_products_ca",
                    django_ckeditor_5.fields.CKEditor5Field(
                        blank=True, verbose_name="Sense Productes (Català)"
                    ),
                ),
                (
                    "no_products_en",
                    django_ckeditor_5.fields.CKEditor5Field(
                        blank=True, verbose_name="No Products (English)"
                    ),
                ),
                (
                    "final_cta_title_ca",
                    django_ckeditor_5.fields.CKEditor5Field(
                        blank=True, verbose_name="Títol CTA Final (Català)"
                    ),
                ),
                (
                    "final_cta_title_en",
                    django_ckeditor_5.fields.CKEditor5Field(
                        blank=True, verbose_name="Final CTA Title (English)"
                    ),
                ),
                (
                    "final_cta_subtitle_ca",
                    django_ckeditor_5.fields.CKEditor5Field(
                        blank=True, verbose_name="Subtítol CTA Final (Català)"
                    ),
                ),
                (
                    "final_cta_subtitle_en",
                    django_ckeditor_5.fields.CKEditor5Field(
                        blank=True, verbose_name="Final CTA Subtitle (English)"
                    ),
                ),
                (
                    "cta_create_product_ca",
                    django_ckeditor_5.fields.CKEditor5Field(
                        blank=True, verbose_name="Crear Producte CTA (Català)"
                    ),
                ),
                (
                    "cta_create_product_en",
                    django_ckeditor_5.fields.CKEditor5Field(
                        blank=True, verbose_name="Create Product CTA (English)"
                    ),
                ),
                (
                    "cta_start_now_ca",
                    django_ckeditor_5.fields.CKEditor5Field(
                        blank=True, verbose_name="Comença Ara CTA (Català)"
                    ),
                ),
                (
                    "cta_start_now_en",
                    django_ckeditor_5.fields.CKEditor5Field(
                        blank=True, verbose_name="Start Now CTA (English)"
                    ),
                ),
                (
                    "cta_have_account_ca",
                    django_ckeditor_5.fields.CKEditor5Field(
                        blank=True, verbose_name="Ja Tinc Compte CTA (Català)"
                    ),
                ),
                (
                    "cta_have_account_en",
                    django_ckeditor_5.fields.CKEditor5Field(
                        blank=True, verbose_name="I Have an Account CTA (English)"
                    ),
                ),
            ],
            options={
                "verbose_name": "Homepage Content",
                "verbose_name_plural": "Homepage Content",
            },
        ),
    ]
