# Generated by Django 5.2.10 on 2026-01-28 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0008_alter_userpurchase_unique_together_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="useraccess",
            name="expiry_date",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
