# Generated by Django 5.0.4 on 2025-11-30 17:20

from django.db import migrations

def delete_old_home_content(apps, schema_editor):
    TranslatableContent = apps.get_model('products', 'TranslatableContent')
    TranslatableContent.objects.filter(key='home_content').delete()

class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_homepagecontent'),
    ]

    operations = [
        migrations.RunPython(delete_old_home_content),
    ]
