# Generated by Django 5.2.10 on 2026-01-28 13:39

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0009_useraccess_expiry_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="useraccess",
            name="activated_at",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
