# Generated by Django 5.2.8 on 2025-11-30 19:27

from django.db import migrations, models


def combine_homepage_content(apps, schema_editor):
    HomePageContent = apps.get_model('products', 'HomePageContent')
    content_instance = HomePageContent.objects.first()

    if not content_instance:
        return

    combined_data = {
        'ca': '',
        'en': '',
    }

    field_prefixes = [
        'kicker', 'cta_title', 'cta_subtitle', 'discover_products', 'create_account',
        'products', 'short_stories', 'browse_catalog', 'add_new_product', 'package',
        'included_titles', 'no_titles_in_package', 'view_details', 'no_products',
        'final_cta_title', 'final_cta_subtitle', 'cta_create_product', 'cta_start_now',
        'cta_have_account'
    ]

    for lang in combined_data.keys():
        html_content = ""
        for prefix in field_prefixes:
            field_name = f"{prefix}_{lang}"
            if hasattr(content_instance, field_name):
                value = getattr(content_instance, field_name)
                if value and value.strip():
                    html_content += f"{value}\n"

        setattr(content_instance, f'content_{lang}', html_content)

    content_instance.save()


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0009_auto_20251130_1720"),
    ]

    operations = [
        migrations.AddField(
            model_name="homepagecontent",
            name="content_ca",
            field=models.TextField(
                blank=True, verbose_name="Home-Page_Content (Català)"
            ),
        ),
        migrations.AddField(
            model_name="homepagecontent",
            name="content_de",
            field=models.TextField(
                blank=True, verbose_name="Home-Page_Content (Deutsch)"
            ),
        ),
        migrations.AddField(
            model_name="homepagecontent",
            name="content_en",
            field=models.TextField(
                blank=True, verbose_name="Home-Page_Content (English)"
            ),
        ),
        migrations.AddField(
            model_name="homepagecontent",
            name="content_es",
            field=models.TextField(
                blank=True, verbose_name="Home-Page_Content (Español)"
            ),
        ),
        migrations.AddField(
            model_name="homepagecontent",
            name="content_fr",
            field=models.TextField(
                blank=True, verbose_name="Home-Page_Content (Français)"
            ),
        ),
        migrations.AddField(
            model_name="homepagecontent",
            name="content_it",
            field=models.TextField(
                blank=True, verbose_name="Home-Page_Content (Italiano)"
            ),
        ),
        migrations.AddField(
            model_name="homepagecontent",
            name="content_pt",
            field=models.TextField(
                blank=True, verbose_name="Home-Page_Content (Português)"
            ),
        ),
        migrations.RunPython(combine_homepage_content),
        migrations.RemoveField(
            model_name="homepagecontent",
            name="add_new_product_ca",
        ),
        migrations.RemoveField(
            model_name="homepagecontent",
            name="add_new_product_en",
        ),
        migrations.RemoveField(
            model_name="homepagecontent",
            name="browse_catalog_ca",
        ),
        migrations.RemoveField(
            model_name="homepagecontent",
            name="browse_catalog_en",
        ),
        migrations.RemoveField(
            model_name="homepagecontent",
            name="create_account_ca",
        ),
        migrations.RemoveField(
            model_name="homepagecontent",
            name="create_account_en",
        ),
        migrations.RemoveField(
            model_name="homepagecontent",
            name="cta_create_product_ca",
        ),
        migrations.RemoveField(
            model_name="homepagecontent",
            name="cta_create_product_en",
        ),
        migrations.RemoveField(
            model_name="homepagecontent",
            name="cta_have_account_ca",
        ),
        migrations.RemoveField(
            model_name="homepagecontent",
            name="cta_have_account_en",
        ),
        migrations.RemoveField(
            model_name="homepagecontent",
            name="cta_start_now_ca",
        ),
        migrations.RemoveField(
            model_name="homepagecontent",
            name="cta_start_now_en",
        ),
        migrations.RemoveField(
            model_name="homepagecontent",
            name="cta_subtitle_ca",
        ),
        migrations.RemoveField(
            model_name="homepagecontent",
            name="cta_subtitle_en",
        ),
        migrations.RemoveField(
            model_name="homepagecontent",
            name="cta_title_ca",
        ),
        migrations.RemoveField(
            model_name="homepagecontent",
            name="cta_title_en",
        ),
        migrations.RemoveField(
            model_name="homepagecontent",
            name="discover_products_ca",
        ),
        migrations.RemoveField(
            model_name="homepagecontent",
            name="discover_products_en",
        ),
        migrations.RemoveField(
            model_name="homepagecontent",
            name="final_cta_subtitle_ca",
        ),
        migrations.RemoveField(
            model_name="homepagecontent",
            name="final_cta_subtitle_en",
        ),
        migrations.RemoveField(
            model_name="homepagecontent",
            name="final_cta_title_ca",
        ),
        migrations.RemoveField(
            model_name="homepagecontent",
            name="final_cta_title_en",
        ),
        migrations.RemoveField(
            model_name="homepagecontent",
            name="included_titles_ca",
        ),
        migrations.RemoveField(
            model_name="homepagecontent",
            name="included_titles_en",
        ),
        migrations.RemoveField(
            model_name="homepagecontent",
            name="kicker_ca",
        ),
        migrations.RemoveField(
            model_name="homepagecontent",
            name="kicker_en",
        ),
        migrations.RemoveField(
            model_name="homepagecontent",
            name="no_products_ca",
        ),
        migrations.RemoveField(
            model_name="homepagecontent",
            name="no_products_en",
        ),
        migrations.RemoveField(
            model_name="homepagecontent",
            name="no_titles_in_package_ca",
        ),
        migrations.RemoveField(
            model_name="homepagecontent",
            name="no_titles_in_package_en",
        ),
        migrations.RemoveField(
            model_name="homepagecontent",
            name="package_ca",
        ),
        migrations.RemoveField(
            model_name="homepagecontent",
            name="package_en",
        ),
        migrations.RemoveField(
            model_name="homepagecontent",
            name="products_ca",
        ),
        migrations.RemoveField(
            model_name="homepagecontent",
            name="products_en",
        ),
        migrations.RemoveField(
            model_name="homepagecontent",
            name="short_stories_ca",
        ),
        migrations.RemoveField(
            model_name="homepagecontent",
            name="short_stories_en",
        ),
        migrations.RemoveField(
            model_name="homepagecontent",
            name="view_details_ca",
        ),
        migrations.RemoveField(
            model_name="homepagecontent",
            name="view_details_en",
        ),
    ]
