# Generated by Django 5.2.9 on 2025-12-20 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0010_remove_homepagecontent_add_new_product_ca_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="category",
            field=models.CharField(
                blank=True, help_text="Categoria del producte", max_length=50
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="duration",
            field=models.IntegerField(
                default=0, help_text="Durada del producte en mesos"
            ),
        ),
        migrations.AddField(
            model_name="userpurchase",
            name="expiry_date",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
