# Generated by Django 5.2.9 on 2025-12-19 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0010_remove_homepagecontent_add_new_product_ca_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="category",
            field=models.CharField(
                choices=[
                    ("dual_start", "Dual Start"),
                    ("dual_progress", "Dual Progress"),
                    ("dual_full_access", "Dual Full Access"),
                ],
                default="dual_start",
                help_text="Categoria del producte",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="duration",
            field=models.IntegerField(
                default=3, help_text="Durada de l'accés en mesos"
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="level",
            field=models.CharField(
                blank=True,
                help_text="Nivell del producte, si s'aplica (p. ex., A2, B1)",
                max_length=2,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="userpurchase",
            name="expiry_date",
            field=models.DateTimeField(
                blank=True,
                help_text="Data de caducitat de l'accés al producte",
                null=True,
            ),
        ),
    ]
