# Generated by Django 5.2.11 on 2026-02-04 20:32

import django.contrib.auth.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0009_customuser_language_code"),
        ("products", "0010_alter_useraccess_activated_at"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserActivityStat",
            fields=[],
            options={
                "verbose_name": "User Activity (Accumulated)",
                "verbose_name_plural": "User Activities (Accumulated)",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("accounts.customuser",),
            managers=[
                ("objects", django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.AlterModelOptions(
            name="useractivity",
            options={
                "verbose_name": "Activity Log",
                "verbose_name_plural": "Activity Logs",
            },
        ),
    ]
