# Generated by Django 5.2.9 on 2025-12-21 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0011_product_category_product_duration_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="title",
            name="human_name",
        ),
        migrations.AddField(
            model_name="titlelanguage",
            name="human_name",
            field=models.CharField(
                default="Default Name",
                help_text="Nom del títol per mostrar en l'idioma especificat",
                max_length=255,
            ),
        ),
    ]
