# Generated by Django 5.2.9 on 2025-12-19 22:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0011_product_category_product_duration_product_level_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="level",
        ),
    ]
