# Generated by Django 5.2.11 on 2026-02-06 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0011_useractivitystat_alter_useractivity_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="stripe_price_id",
            field=models.CharField(
                blank=True, help_text="Stripe Price ID", max_length=255, null=True
            ),
        ),
        migrations.AddField(
            model_name="userpurchase",
            name="stripe_checkout_id",
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
