# Generated by Django 5.2.9 on 2025-12-20 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0011_product_category_product_duration_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="title",
            name="human_name",
        ),
        migrations.AddField(
            model_name="titlelanguage",
            name="human_name",
            field=models.CharField(
                default="", help_text="Nom del títol en aquest idioma", max_length=255
            ),
        ),
    ]
