# Generated by Django 5.2.9 on 2026-01-03 23:51

from django.db import migrations

def populate_sales_conditions(apps, schema_editor):
    TranslatableContent = apps.get_model('products', 'TranslatableContent')
    TranslatableContent.objects.update_or_create(
        key='product_terms',
        defaults={
            'content_ca': """
                <h3>1. Objecte</h3>
                <p>Les presents Condicions Generals de Venda tenen per objecte regular la relació contractual de compravenda nascuda entre el Venedor i el Client en el moment en què aquest accepta durant el procés de contractació en línia la casella corresponent.</p>
                <h3>2. Durada</h3>
                <p>La relació contractual s'entendrà formalitzada des del moment de la compra i tindrà la durada corresponent al període de subscripció seleccionat pel Client.</p>
                <h3>3. Preu i forma de pagament</h3>
                <p>El preu del servei serà el que s'indiqui en la nostra pàgina web en el moment de la compra. El pagament es realitzarà mitjançant targeta de crèdit o dèbit a través de la passarel·la de pagament segura.</p>
                <h3>4. Obligacions del Client</h3>
                <p>El Client es compromet a utilitzar el servei de forma diligent i correcta, així com a facilitar dades veraces en el procés de registre i compra.</p>
            """,
            'content_en': """
                <h3>1. Object</h3>
                <p>The purpose of these General Conditions of Sale is to regulate the contractual sales relationship born between the Seller and the Client at the moment the Client accepts the corresponding box during the online contracting process.</p>
                <h3>2. Duration</h3>
                <p>The contractual relationship will be understood to be formalized from the moment of purchase and will have the duration corresponding to the subscription period selected by the Client.</p>
                <h3>3. Price and method of payment</h3>
                <p>The price of the service will be that indicated on our website at the time of purchase. Payment will be made by credit or debit card through the secure payment gateway.</p>
                <h3>4. Obligations of the Client</h3>
                <p>The Client agrees to use the service diligently and correctly, as well as to provide truthful data in the registration and purchase process.</p>
            """,
            # Add other languages as needed
        }
    )

class Migration(migrations.Migration):

    dependencies = [
        ("products", "0012_remove_title_human_name_titlelanguage_human_name"),
    ]

    operations = [
        migrations.RunPython(populate_sales_conditions),
    ]
