# Generated by Django 5.2.9 on 2026-01-04 00:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0013_alter_titlelanguage_human_name'),
        ('products', '0013_populate_sales_conditions'),
    ]

    operations = [
    ]
