# Generated by Django 5.2.9 on 2026-01-04 00:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0013_populate_sales_conditions"),
    ]

    operations = [
        migrations.AlterField(
            model_name="titlelanguage",
            name="human_name",
            field=models.CharField(
                help_text="Nom del títol per mostrar en l'idioma especificat",
                max_length=255,
            ),
        ),
        migrations.CreateModel(
            name="ProductTranslation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("language_code", models.CharField(max_length=10)),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True)),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="translations",
                        to="products.product",
                    ),
                ),
            ],
            options={
                "verbose_name": "Traducció de Producte",
                "verbose_name_plural": "Traduccions de Producte",
                "unique_together": {("product", "language_code")},
            },
        ),
    ]