# Generated by Django 5.2.9 on 2026-01-04 00:20

from django.db import migrations

class Migration(migrations.Migration):

    dependencies = [
        ('products', '0015_migrate_product_data'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='name',
        ),
        migrations.RemoveField(
            model_name='product',
            name='description',
        ),
    ]
